### ISSUE TITLE
du.zoomquiet.io 已经变更为 du.101.camp

### ISSUE THREAD

**Issue by ZoomQuiet** [RSS-Renaissance/awesome-blogCN-feeds#3]
非常不好意思...

- 这个 blog 原本就是自学社区 => 自怼圈 的团队blog
- 之前一直没有合适的域名来挂栽
- 这个月正式迁移为:
    + [Home ~ DebugUself with DAMA ;-)](https://du.101.camp/)
    + RSS 不变: https://du.101.camp/atom.xml
- 而俺私人的 blog 前后有过很多, 最终保留下来的:
    + [/ 是也乎(￣▽￣) / ZoomQuiet.io](https://blog.zoomquiet.io/)
        * https://blog.zoomquiet.io/feeds/all.atom.xml
    + [Zoom.Quiet's PyBlosxom blogging](http://blog.zoomquiet.top/pyblosxom/)
        * http://blog.zoomquiet.top/pyblosxom/index.atom

是也乎,(￣▽￣) -> [添加： Home | DebugUself with DAMA ;-) http://du.zoomquiet.io/ · RSS-Renaissance/awesome-blogCN-feeds@362ecfe](https://github.com/RSS-Renaissance/awesome-blogCN-feeds/commit/362ecfe6b6266ebdb9977bf084335fdbffe0cc59)

**Comment by xianmin** [comment]
感谢提醒！已经更正。 :smile:
